baseURL: ''  # TODO: must be changed
theme: hugobricks
defaultContentLanguage: it
assetDir: static

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in md files

languages:
  it:
    languageName: Italiano
    contentDir: content/it
    weight: 1
    disabled: false
